apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ewp-server-dr
  namespace: ewp
spec:
  host: ewp-server.ewp.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 10000
        maxRequestsPerConnection: 0
        h2UpgradePolicy: UPGRADE
      tcp:
        maxConnections: 1000
        connectTimeout: 10s
        tcpKeepalive:
          time: 300s
          interval: 30s
          probes: 5
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
  subsets:
    - name: grpc-upstream
      labels:
        app: ewp-server
      trafficPolicy:
        connectionPool:
          http:
            http2MaxRequests: 10000
            maxRequestsPerConnection: 0
            h2UpgradePolicy: UPGRADE
          tcp:
            maxConnections: 1000
            tcpKeepalive:
              time: 300s
              interval: 30s
              probes: 5
